# Generated by Django 5.1.1 on 2024-10-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merp_app', '0004_alter_reservation_reservation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_code',
            field=models.CharField(default='TWJS1LA', editable=False, max_length=6, unique=True),
        ),
    ]
